### ISSUE TITLE
Handle missing packages gracefully in appimage-builder --generate

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/appimage-builder#101]
> I wonder why it's trying to download from `https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_6 ` heads up on the end `x86_6` where it should be `x86_64`. Are you writing it properly in the yaml file ?

oh yes it was x86_6.
thanks

N.B: it work but it used different gtk theme in comparison to flatpak version and the official version here an example: https://github.com/bottlesdevs/Bottles/issues/156#issuecomment-796665063
In addition running `appimage-builder --generate` will result in the following:
```bash
Traceback (most recent call last):
  File "/home/user/.local/bin/appimage-builder", line 33, in <module>
    sys.exit(load_entry_point('appimage-builder==0.8.5', 'console_scripts', 'appimage-builder')())
  File "/home/user/.local/lib/python3.6/site-packages/appimagebuilder/__main__.py", line 77, in __main__
    generator = RecipeGenerator()
  File "/home/user/.local/lib/python3.6/site-packages/appimagebuilder/generator/generator.py", line 70, in __init__
    runtime_analyser.runtime_libs
  File "/home/user/.local/lib/python3.6/site-packages/appimagebuilder/generator/apt_recipe_generator.py", line 41, in resolve_includes
    packages = AptRecipeGenerator._map_files_to_packages(runtime_libs)
  File "/home/user/.local/lib/python3.6/site-packages/appimagebuilder/generator/apt_recipe_generator.py", line 50, in _map_files_to_packages
    packages = dpkg_query.search(runtime_libs)
  File "/home/user/.local/lib/python3.6/site-packages/appimagebuilder/commands/dpkg_query.py", line 31, in search
    raise DpkgQueryError("Package lockup failed")
````

_Originally posted by @hthre7 in https://github.com/AppImageCrafters/appimage-builder/issues/99#issuecomment-796850927_

**Comment by hthre7** [comment]
running appimage-builder --generate:
`
WARNING:root:No dependencies were found, please make sure that all the required libraries are reachable.
INFO:Generator:Guessing APT configuration
INFO:Generator:Resolving dependencies packages
INFO:dpkg-query:/usr/bin/dpkg-query -S
WARNING:dpkg-query:dpkg-query: error: --search needs at least one file name pattern argument
WARNING:dpkg-query:
WARNING:dpkg-query:Use --help for help about querying packages.
INFO:dpkg-query:/usr/bin/dpkg-query -W -f=${binary:Package}: ${Depends}\n
INFO:Generator:No desktop entries found
`

**_here is the libs:_**
`
INFO:Generator:Analysing application runtime dependencies
INFO:AppRuntimeAnalyser:/usr/bin/strace -ff -e trace=openat -E LD_LIBRARY_PATH=/home/user/Applications/Bottles-master/AppDir/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules:/home/user/Applications/Bottles-master/AppDir/usr/lib/aspell/x86_64-linux-gnu:/home/user/Applications/Bottles-master/AppDir/usr/lib/python3.8/config-3.8-x86_64-linux-gnu:/home/user/Applications/Bottles-master/AppDir/usr/lib/x86_64-linux-gnu/enchant-2:/home/user/Applications/Bottles-master/AppDir/opt/libc/usr/lib/x86_64-linux-gnu/gconv:/home/user/Applications/Bottles-master/AppDir/usr/lib/x86_64-linux-gnu/gio/modules:/home/user/Applications/Bottles-master/AppDir/usr/lib/x86_64-linux-gnu:/home/user/Applications/Bottles-master/AppDir/usr/lib/x86_64-linux-gnu/glade/modules:/home/user/Applications/Bottles-master/AppDir/lib/x86_64-linux-gnu/security:/home/user/Applications/Bottles-master/AppDir/lib/x86_64-linux-gnu:/home/user/Applications/Bottles-master/AppDir/usr/lib/x86_64-linux-gnu/gtk-2.0/2.10.0/engines:/home/user/Applications/Bottles-master/AppDir/opt/libc/lib/x86_64-linux-gnu:/home/user/Applications/Bottles-master/AppDir/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/printbackends:/home/user/Applications/Bottles-master/AppDir/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders:/home/user/Applications/Bottles-master/AppDir/opt/libc/usr/lib/x86_64-linux-gnu/krb5/plugins/preauth:/home/user/Applications/Bottles-master/AppDir/opt/libc/lib64:/home/user/Applications/Bottles-master/AppDir/usr/lib/x86_64-linux-gnu/gstreamer-1.0:/home/user/Applications/Bottles-master/AppDir/opt/libc/usr/lib/x86_64-linux-gnu /home/user/Applications/Bottles-master/AppDir/usr/bin/bottles $@
`

**Comment by azubieta** [comment]
@hthre7 could you try using the latest code from master. I pushed a fix that should generate a better recipe.

**Comment by hthre7** [comment]
> @hthre7 could you try using the latest code from master. I pushed a fix that should generate a better recipe.

the one before 4 days, yes already tried and the result is above(https://github.com/AppImageCrafters/appimage-builder/issues/101#issuecomment-797917307) that what I got
