### ISSUE TITLE
APT update error on Linux Mint 19.3

### ISSUE THREAD

**Issue by nicolalandro** [AppImageCrafters/appimage-builder#111]
I try to do the [pyqt example](https://github.com/AppImageCrafters/appimage-builder/tree/master/examples/pyqt5) but when I try to make the appimage I have an error:

```
$ appimage-builder --recipe AppImageBuilder.yml --skip-test
INFO:root:======
INFO:root:Script
INFO:root:======
rm -rf AppDir  | true
mkdir -p AppDir/usr/src
cp main.py  AppDir/usr/src -r
python3 -m pip install --ignore-installed --prefix=/usr --root=AppDir -r ./requirements.txt
Collecting pyfiglet
  Using cached pyfiglet-0.8.post1-py2.py3-none-any.whl (865 kB)
Installing collected packages: pyfiglet
  WARNING: The script pyfiglet is installed in 'AppDir/usr/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pyfiglet-0.8.post1
INFO:root:=================
INFO:root:Generating AppDir
INFO:root:=================
INFO:root:
INFO:root:Bundling dependencies
INFO:root:---------------------
INFO:apt:apt-get update
E: Errore di sintassi /media/mint/Barracuda/appimage example/appimage-builder-cache/apt/apt.conf:1: caratteri extra dopo il valore
ERROR:root:"apt-get update" execution failed
Traceback (most recent call last):
  File "/home/mint/.local/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/home/mint/.local/lib/python3.6/site-packages/appimagebuilder/__main__.py", line 94, in __main__
    creator.build()
  File "/home/mint/.local/lib/python3.6/site-packages/appimagebuilder/builder/builder.py", line 62, in build
    self._bundle_dependencies()
  File "/home/mint/.local/lib/python3.6/site-packages/appimagebuilder/builder/builder.py", line 84, in _bundle_dependencies
    packages, self.app_dir_path, packages_excluded
  File "/home/mint/.local/lib/python3.6/site-packages/appimagebuilder/builder/deploy/apt/deploy.py", line 36, in deploy
    self._prepare_apt_venv()
  File "/home/mint/.local/lib/python3.6/site-packages/appimagebuilder/builder/deploy/apt/deploy.py", line 45, in _prepare_apt_venv`
    self.apt_venv.update()
  File "/home/mint/.local/lib/python3.6/site-packages/appimagebuilder/builder/deploy/apt/venv.py", line 160, in update
    shell.assert_successful_result(_proc)
  File "/home/mint/.local/lib/python3.6/site-packages/appimagebuilder/common/shell.py", line 31, in assert_successful_result
    '"%s" execution failed with code %s' % (proc.args, proc.returncode)
RuntimeError: "apt-get update" execution failed with code 100
```

But If I do `sudo apt update` I do not have problems.

Can someone help me?

**Comment by azubieta** [comment]
@nicolalandro could you provide a log in English, or translate the following line for me?

`E: Errore di sintassi /media/mint/Barracuda/appimage example/appimage-builder-cache/apt/apt.conf:1: caratteri extra dopo il valore
`

**Comment by nicolalandro** [comment]
Scuseme, it says: `Sintax Error /media/mint/Barracuda/appimage example/appimage-builder-cache/apt/apt.conf:1: extra characters after the value`.
But I do not touch the example, I only try to run.
(Scuse me again for the language)

**Comment by azubieta** [comment]
Maybe there was a copy paste error and some hidden char is being copied is causing the apt.conf to break. Could you try to look into it (and maybe share it) to see what's wrong?

> (Scuse me again for the language)

No worries :)

**Comment by nicolalandro** [comment]
I check all think and at the I end I try this that can be easly reproduced:
```
$ git clone https://github.com/AppImageCrafters/appimage-builder.git
$ cd appimage-builder/examples/pyqt5/
$ appimage-builder --recipe AppImageBuilder.yml --skip-test
```

**Comment by azubieta** [comment]
When python3 is used from the system like in this scenario you must make sure that the version match the one deployed in the AppDir. Otherwise it will deploy the libraries in a different path. Check that the PYTHONPATH variable set in the `AppDir > runtime > env` section points to the right path where `pyfiglet` is deployed, if not, try to change it.

In case your system has a different python version than the one contained in your bundle. You can use the same method that is used in the youtube-dl AppImage recipe:

https://github.com/AppImageCrafters/youtube-dl-appimage/blob/5f1ae25aa7efa0937f905f5f1717a703f561a53f/appimage-builder.yml#L44-L58

**Comment by azubieta** [comment]
Closing it as resolved. I moved your second problem into a new issue #131
