### ISSUE TITLE
Bug: tester/execution_test.py: Attempt to create an existing user

### ISSUE THREAD

**Issue by pzhlkj6612** [AppImageCrafters/appimage-builder#117]
Hi. I tried to test a Qt-based program in Docker containers but got an error about creating the already existing user "root".

## Environment

I didn't configure the [rootless running mode](https://docs.docker.com/engine/security/rootless/) of Docker daemon, so `sudo` is required.

```console
$ uname -r
5.4.0-56-generic

$ lsb_release -d
Description:	Ubuntu 20.04.1 LTS

$ python3 --version
Python 3.8.5

$ pip3 freeze | grep -e 'appimage-builder' -e 'docker'
appimage-builder==0.8.7
docker==4.4.4

$ sudo docker --version
Docker version 20.10.5, build 55c4c88
```

I also tried the continuous build from 2ccd43c1f00009cf8cfec71334a0f26da105edb4 and got the same error.

## Reproduce details

The most important part of my *recipe.yml*:

```yaml
version: 1
AppDir:
  ...
  test:
    any_test:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true
      env:
        QT_DEBUG_PLUGINS: 1
    ...
...
```

Call *appimage-builder* with root privilege:

```console
$ sudo appimage-builder --recipe recipe.yml --skip-script --skip-build --skip-appimage
INFO:root:============
INFO:root:AppDir tests
INFO:root:============
INFO:root:
INFO:root:Running test: any_test
INFO:root:-----------------------------
INFO:TEST CASE 'any_test':before command
$ useradd -mu 0 root
useradd: user 'root' already exists

$ useradd -mu 0 root FAILED, exit code: 9
ERROR:appimage-builder:Tests failed
ERROR:appimage-builder:
```

### Why create the user

I *guess* that this user creation is for the Xserver connection and authority.

Assuming that the user who logs into the desktop and runs Docker daemon is "foo", if the user has been added to the container and runs the GUI program in it, the program's window will be sent to the Xserver which runs the desktop without any manual configuration. If not, the user will have to execute the following command to allow the Xserver connection:

```console
$ xhost +si:localuser:foo
localuser:foo being added to access control list
```

Otherwise, that program (here is a Qt-based program) will not run successfully:

```console
...
loaded library "/app/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
No protocol specified
qt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
...
```

Please correct me if I am wrong.

### Why error occurred

Look at the code:

```python
#...
    def run(self):
#...
            self._run_command(
                "useradd -mu %s %s" % (os.getuid(), os.getenv("USER")), container
            )
#...
    def _run_command(self, command, container, user="root"):
        print("$ %s" % command)
        exit_code, output = container.exec_run(command, user=user, tty=True)
        print(output.decode())

        if exit_code != 0:
            print("$ %s FAILED, exit code: %s" % (command, exit_code))
            raise TestFailed()
```

https://github.com/AppImageCrafters/appimage-builder/blob/2ccd43c1f00009cf8cfec71334a0f26da105edb4/appimagebuilder/tester/execution_test.py#L63-L65

https://github.com/AppImageCrafters/appimage-builder/blob/2ccd43c1f00009cf8cfec71334a0f26da105edb4/appimagebuilder/tester/execution_test.py#L77-L85

`useradd` will return 9 if the username is already in use ([man page](https://www.man7.org/linux/man-pages/man8/useradd.8.html#EXIT_VALUES)), and the script will fail if the exit code of `exec_run` does not equal 0.

#### Use `getent`

We can `getent` the username (or uid? I think username is better) to determine if we need to create the user:

```diff
              self._run_command(
-                 "useradd -mu %s %s" % (os.getuid(), os.getenv("USER")), container
+                 "sh -c 'getent passwd %s || useradd -mu %s %s'" % (os.getenv("USER"), os.getuid(), os.getenv("USER")), container
              )
```

#### Why use `sh -c`

According to [docker exec | Docker Documentation § Extended description](https://docs.docker.com/engine/reference/commandline/exec/#extended-description), *a chained or a quoted command will not work*.

<br>

Over.

**Comment by azubieta** [comment]
Maybe we can accept 9 as a valid exit code, It would imply modifying the _run_command method to define which codes are accepted as valid.

**Comment by azubieta** [comment]
@pzhlkj6612 could you please try using the version from https://github.com/AppImageCrafters/appimage-builder/pull/118 ?

**Comment by pzhlkj6612** [comment]
@azubieta It works! :)
