### ISSUE TITLE
Please make icon optional

### ISSUE THREAD

**Issue by baryluk** [AppImageCrafters/appimage-builder#127]
I am trying to use appimage-builder to package some CLI applications and number of small tools. They don't have icons, and I don't want to specific icon, or generate `.desktop` files, but right now I need to put some dummy icon anyway.

`appimage-builder` will fail at the moment, if the icon is not specified, it is not a string, or can't be located.

I am using appimage-builder 0.8.8 from pip3 .

**Comment by azubieta** [comment]
Having an Icon and a desktop file is a requirement is enforced by appimagetool (a low level tool for making AppImages), what we could to is to set a default one from the appimage-builder.

**Comment by baryluk** [comment]
@azubieta Thank you for making it optional / default.
