### ISSUE TITLE
Dockerfile missing strace

### ISSUE THREAD

**Issue by zifik** [AppImageCrafters/appimage-builder#143]
`apt-get -y install strace` is missing from Dockerfile.  Can't use commands like `appimage-builder --generate` inside of a Docker container.

**Comment by azubieta** [comment]
The generate is meant to be used where the application runs, which provably is not inside the docker container. That's why we didn't include it.

You can use the AppImage from the releases instead if you need a simple way to run appimage-builder, or install it using python pip.

**Comment by zifik** [comment]
Can you elaborate on the purpose of building it into a Docker image then? It's not clear to me from reviewing the docs: https://appimage-builder.readthedocs.io/en/latest/intro/install.html

I figured it was so that if I preferred to run without installing locally I could do something like:

```bash
docker run --rm -it -v $(pwd):/src -w /src appimagecrafters/appimage-builder /bin/bash -c "apt-get update && appimage-builder"
```

Regardless, the pip3 install is certainly a feasible alternative for my situation, I'll just stick with that for now.

**Comment by azubieta** [comment]
The Docker image is a convenience for creating AppImages on Github Actions, Gitlab Pipelines, or other CI solutions capable of using docker. I guess that this must be included in the documentation for clarity.

**Comment by zifik** [comment]
I see, so the assumption is that the project has already been properly configured and has all of the necessary files, hence no need for `strace`.   

Yes, the clarity would help, but here are some additional thoughts to consider for the Docker image being built and a greater explanation of my attempted usage.

Due to the development constraints placed on our team for working on remote servers, we have opted to completely source control our entire development environment using VSCode Remote Development (https://code.visualstudio.com/docs/remote/remote-overview)  

In such an environment, I would much rather be able to run a container that contains all of the appimage and appimage-builder runtimes and their dependencies than to have to install them on the host or figure it out for my other development containers. Much like in a CI environment.

Would it be too much to ask for a "feature request" in that you fluff up the Dockerfile for this project a bit to be fully functional for all appimage and appimage-builder features?

For example, being able to run `docker run --rm -it -v $(pwd):/src -w /src appimagecrafters/appimage-builder --generate` or `docker run --rm -it -v $(pwd):/src -w /src appimagecrafters/appimage-builder --help`  would be pretty slick. 

It think that this could be done without impacting any current usages of the docker image that exist out there.

**Comment by azubieta** [comment]
Didn't knew about VSCode Remote Development, looks really interesting.

> It think that this could be done without impacting any current usages of the docker image that exist out there.

Agreed, let's do it.
