### ISSUE TITLE
gdk-pixbuf-query-loaders not found on fedora

### ISSUE THREAD

**Issue by fbdtemme** [AppImageCrafters/appimage-builder#149]
In fedora 34 the package `gdk-pixbuf2` does not provide `gdk-pixbuf-query-loaders`, but provides a `gdk-pixbuf-query-loaders-64`.
This will cause and error notifying that `gdk-pixbuf-query-loaders` is not found.
This issue is easily resolved with symlinking, but I think it would be nice if it works without user intervention.

**Comment by azubieta** [comment]
> I think it would be nice if it works without user intervention.

Indeed, would you like to make a PR ?

https://github.com/AppImageCrafters/appimage-builder/blob/master/appimagebuilder/modules/setup/helpers/gdk_pixbuf.py#L59-L70
