### ISSUE TITLE
appimagetool ignores ARCH env variable when AppImage.arch is set to 'aarch64'

### ISSUE THREAD

**Issue by smanhaeve** [AppImageCrafters/appimage-builder#154]
appimagetool only accepts `arm_aarch64` as value for the `ARCH` environment variable. (see [`extract_arch_from_text` in appimagetool.c](https://github.com/AppImage/AppImageKit/blob/1681fd84dbe09c7d9b22e13cdb16ea601aa0ec47/src/appimagetool.c#L336))

When building a recipe for aarch64, this will cause appimagetool to ignore the `ARCH` environment variable set by appimage-builder, falling back to guessing the appropriate architecture based on the executable libraries in the AppDir. This will fail with the following error message if the appdir contains libraries or library-like files that are not targeting aarch64:
```
More than one architectures were found of the AppDir source directory "./AppDir"
A valid architecture with the ARCH environmental variable should be provided
e.g. ARCH=x86_64 appimagetool ...
```

**Comment by n00bsys0p** [comment]
I ran into the same thing today. The temporary workaround for this that I'm currently is to manually symlink the runtime in `appimage-builder-cache` before building. appimage-builder only downloads the runtime file if it doesn't exist, so downloading the runtime file manually and then symlinking it before running appimage-builder at least allows the build to succeed.

```shell
mkdir -p appimage-builder-cache
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-aarch64 -O appimage-builder-cache/runtime-aarch64
ln -s runtime-aarch64 appimage-builder-cache/runtime-arm_aarch64
appimage-builder
```

**Comment by n00bsys0p** [comment]
I've created a PR that resolves this issue - see linked PR above.
