### ISSUE TITLE
Question: Why move glibc related files to /opt/glibc?

### ISSUE THREAD

**Issue by jclab-joseph** [AppImageCrafters/appimage-builder#156]
**THIS IS NOT ISSUE** Just question :)

**Why move glibc related files to /opt/glibc?**

https://github.com/AppImageCrafters/appimage-builder/blob/adf69b9ded4d3e734f753e2cd4a842ab1e20427b/appimagebuilder/modules/deploy/files/deploy_helper.py

**Comment by azubieta** [comment]
To be able to exclude it from the linker lockup path if required. If you have a better idea of how to do it feel free to share it.

Long story: https://azubieta.net/p/how-to-switch-the-ld.so-used-by-a-binary-at-runtime/

**Comment by jclab-joseph** [comment]
@azubieta Thank you.
By the way, exactly, I wonder why glibc needs to be in appimage_mount/opt/glibc instead of appimage_mount/lib.

**Comment by azubieta** [comment]
When creating the AppImage we try to change the installation paths as less as possible. Therefore some other files may be deployed into `$APPDIR/lib` therefore se use a non standard path to isolate our copy of glibc and other libs that are tightly related

**Comment by jclab-joseph** [comment]
I'm sorry I didn't understand well.
I wonder why you need to change the location of glibc installed in AppImage in order to use the optimal glibc.
Already the paths of /lib/glibc.so and $APPDIR/lib/glibc.so are different, so I wonder why they need to be moved additionally.
Can you tell me where the code related to this is located? Then I think you can understand better.

**Comment by azubieta** [comment]
Oh, we are not only separating it from the system libraries but also from other libraries in the bundle. As said other libs may end up at /lib and we don't want them to be excluded when we exclude the libc. Actually in arch systems all libs goes to /lib
