### ISSUE TITLE
Consider using /bin/sh and changing mktemp call to make it work on FreeBSD, too

### ISSUE THREAD

**Issue by probonopd** [AppImageCrafters/appimage-builder#157]
Would it be possible to change `#! /bin/bash` to `#! /bin/sh` in all scripts that end up in the AppImages? This would improve compatibility, e.g., with FreeBSD, where `/bin/bash` does not exist (even if you install bash from Ports).

This line in `apprun-hooks/linuxdeploy-plugin-gtk.sh` breaks on FreeBSD and possibly on other systems:

```
CACHEDIR="$(mktemp --tmpdir --directory .AppRun.XXXXXXXX)"
```

If I change this for testing to

```
CACHEDIR=$(mktemp  -d  "/tmp/.AppRun.XXXXXXXX")
```

then the application runs.

The culprit is:

```
FreeBSD% mktemp --tmpdir --directory .AppRun.XXXXXXXX
mktemp: illegal option -- -
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
```

As per https://www.freebsd.org/cgi/man.cgi?mktemp, `mktemp  -d  "/tmp/.AppRun.XXXXXXXX"` works for me on FreeBSD but I have not tested it on Linux.

![image](https://user-images.githubusercontent.com/2480569/136906825-482ebc75-a48e-4216-b31e-9d8c581c5028.png)

Reference:
https://github.com/geany/geany/issues/1303#

**Comment by probonopd** [comment]
I am "only" talking about the scripts that become part of the produced AppImage. So that the produced AppImage doesn't need bash.

**Comment by probonopd** [comment]
Oops. Sorry for the noise. I totally screwed this. Sorry!

**Comment by azubieta** [comment]
No worries :smile:
