### ISSUE TITLE
Wrong icon search path

### ISSUE THREAD

**Issue by technic** [AppImageCrafters/appimage-builder#177]
Hi,

the icon is searched in `AppDir/usr/share` instead if `AppDir/share`

this is what I see in the logs

```
INFO:main:Running desktop entry setup
INFO:root:Looking app icon at: /root/appdir/usr/share/icons
INFO:root:Looking app icon at: /root/appdir/usr/share/pixmaps
INFO:root:Looking app icon at: /usr/share/icons
INFO:root:Looking app icon at: /usr/share/pixmaps
```

**Comment by azubieta** [comment]
`usr/share` is the expected path we also search for icon on `usr/local/share`

**Comment by azubieta** [comment]
> should I use AppDir/usr as prefix for my cmake install 
yes

> I believe in the docs it was just AppDir/bin and AppDir/share.
Need to clarify that.

**Comment by technic** [comment]
> Need to clarify that.

Maybe I confused with some other tool, like linuxdeployqt. I think your manual is correct. Sorry for bothering :)
