### ISSUE TITLE
Qt Release Folder to Appimage?

### ISSUE THREAD

**Issue by EmrahErden** [AppImageCrafters/appimage-builder#180]
I tried and tested the tutorial, which uses qt-appimage-template.git. And yes it works in my laptop:

https://appimage-builder.readthedocs.io/en/latest/intro/tutorial.html

When comes to applying it to the a custom qt release folder (build-Qt_ .... -Desktop_Qt_6_2_3_GCC_64bit-Release), i see zero similarity with the template given in the tutorial. This is the release folder:

![Screenshot from 2022-02-10 22-58-15](https://user-images.githubusercontent.com/8374137/153487335-1a779de6-eb80-45ff-877b-6205e83e5d68.png)

How can i convert it to work with appimage-builder, or i'm in a very wrong place?

Using:
Qt 6.2.2 (GCC 10.3.1 20210422 (Red Hat 10.3.1-1), 64 bit)
Ubuntu 20.04

**Comment by azubieta** [comment]
If it's appimage-builder related you're in the right place :smile: 

In the tutorial we use the Qt5 binaries ship from the Ubuntu repositories therefore if you use a different kind of package it's normal to have a different project structure in the resulting appimage. 

By the way I haven't tested Qt6, please feel free to share your impressions and any issues you found.
