### ISSUE TITLE
Apt deploy: cache keys

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/appimage-builder#184]
Avoid downloading key files by making a cache of them

ref: #181

**Comment by goldstar611** [comment]
I would also like this to be able to build offline. AppImage caches all of the *.deb packages it needs so most of the work is done to build offline.

**Comment by azubieta** [comment]
Use `ABUILDER_APT_SKIP_UPDATE=1` to prevent AppImage Builder from running apt-get update. If in a previous run you already fetched all your packages it should work.

**Comment by azubieta** [comment]
I wonder why I have this open, this is already done. Cache files are being stored after download.
