### ISSUE TITLE
AppImage build fails when path contains # character

### ISSUE THREAD

**Issue by RastislavKish** [AppImageCrafters/appimage-builder#188]
I have my projects organized in folders according to the used programming language.
Trying to build an appimage-builder recipe in C# folder always results in apt-get update fail, error code 100.

## Reproduction steps

1. Create a folder with a name containing # character i.e. C#.
2. Inside this folder, try to build any appimage-builder recipe (subfolders don't make a difference)

## Expected behavior

Build proceeds as in any other folder.

## Actual behavior

During the build, apt-get update fails with error code 100.

## Environment

Ubuntu Mate 20.04 64-bit

appimage-builder 0.9.2 stable (tested with the git version as well, resulting in the same behavior)

**Comment by azubieta** [comment]
Please feel free to reopen if the issue persist.
