### ISSUE TITLE
The documentation doesn't mention the AppImage release

### ISSUE THREAD

**Issue by Toasterbirb** [AppImageCrafters/appimage-builder#196]
I came across [this](https://appimage-builder.readthedocs.io/en/latest/intro/install.html) documentation site when trying to figure out how to install the appimage-builder tool. The site shows how to download the appimagetool AppImage, but for appimage-builder there are only instructions for installing with pip and docker.

I didn't even know that appimage-builder also had an AppImage until I came across this github repo.
Is this intentional?

**Comment by azubieta** [comment]
Oh, I have missed it when writing the documentation.

Sorry, feel free to make a PR with changes to https://github.com/AppImageCrafters/appimage-builder-docs

**Comment by Toasterbirb** [comment]
I'd be glad to have a try with that, but I'm having issues building the documentation. The python version that the project uses has reached end of life on my linux distribution. I got around that but the `make html` command errors out with `Could not import extension recommonmark (exception: No module named 'recommonmark')` in the pipenv environment.

I'm not familiar with python at all and I actually didn't even have pip installed on my system before this so I don't know if I'm really fit for solving this issue

**Comment by azubieta** [comment]
Fixed, the instructions can be found at https://appimage-builder.readthedocs.io/en/latest/intro/install.html#appimage
