### ISSUE TITLE
`$APPDIR` is empty inside `after_bundle`

### ISSUE THREAD

**Issue by alex-tee** [AppImageCrafters/appimage-builder#213]
Since a few days ago, `$APPDIR` is empty inside the `after_bundle` section of the YAML

See towards the end here: https://azusa.runners.sr.ht/logs/736746/make-appimage/log

I am doing `echo $APPDIR` as the first command inside  `after_bundle` and it returns an empty string

**Comment by azubieta** [comment]
@alex-tee sorry about that. We had to change it from `APPDIR` to `TARGET_APPDIR` as it clashed with the bundle variable with `appimage-builder` is used as an AppImage.
