### ISSUE TITLE
Consider making Docker test cases container volumes writable

### ISSUE THREAD

**Issue by AlexTMjugador** [AppImageCrafters/appimage-builder#214]
While writing test cases for the arguably not very well supported use case of running AppImages generated with appimage-builder on Alpine Linux (a musl-based environment), I've stumbled upon a behavior change from v0.9.2 in v1.0.0-alpha.1 onwards, apparently caused by https://github.com/AppImageCrafters/appimage-builder/commit/a44066ce4783dfb8093727c48b0a3a6b74fcc6d8: glibc-related files are now copied to `runtime/compat`, instead of their usual `/lib`, `/lib64` and similar folders.

To get the AppImage running on Alpine, previously it was enough to extract it on a glibc host and copy the AppDir contents to the root directory of the Alpine environment. This worked for me, as I'm using Alpine in disposable Docker containers, and it also worked on the test cases specified in the recipe too.

However, now it's necessary to run a command like `cp -R /runtime/compat/* /` for the AppRun executable to work on such an environment. The AppRun executable itself never ran anyway, because it's linked against glibc. I confirmed running that command worked on a disposable Docker container, but when changing the test case command to `sh -c 'cp -R runtime/compat/* . && ./AppRun --version'` in order to perform the copy before running the application, I was greeted with errors like:

```
cp: can't create directory './etc/ld.so.conf.d': Read-only file system
cp: can't create './lib/x86_64-linux-gnu/libgcc_s.so.1': Read-only file system
cp: can't create './lib/x86_64-linux-gnu/ld-2.33.so': Read-only file system
cp: can't create './lib/x86_64-linux-gnu/libBrokenLocale-2.33.so': Read-only file system
cp: can't create './lib/x86_64-linux-gnu/libSegFault.so': Read-only file system
cp: can't create './lib/x86_64-linux-gnu/libanl-2.33.so': Read-only file system
cp: can't create './lib/x86_64-linux-gnu/libc-2.33.so': Read-only file system
```

Given that modifying the test container filesystem is necessary to get the application to work, this is a regression in behavior for my use case from v0.9.2. I'd be very happy if the container filesystem was just made writable, but maybe it'd not be a bad idea to support Alpine better in general, if it's in scope for this project. I could help :smile:

**Comment by azubieta** [comment]
Hello @AlexTMjugador as you already noticed some changes were made in the way glibc is dealt with which needs to be documented at some point. I'll try to make a quick summary for you. 

In "v0.9" we patched the executable elf files with a linker path on `/tmp/appimage-xxxxxxx-ld-linux.so` but this is an open vector for attacker who may replace that file and sneak into the application execution workflow. Therefore we moved on using relative paths for all interpreters on "v1". Now, before executing any bundled binary (or script) we chdir to `APPDIR/runtime/compat` (or `APPDIR/runtime/default` in case the system libc is newer that the one bundled). This makes the relative path valid and allows the resolution of the `ld-linux.so` or other interpreter after that we restore the working directory to the original location.

Regarding the AppRun now being a dynamically linked executable is because right now the only reliable way of getting the system libc version we know is by calling `gnu_get_libc_version`. I have a [StackOverflow question on this topic](https://stackoverflow.com/questions/71070969/how-to-extract-and-compare-the-libc-versions-at-runtime) it would be great if you could help use find a way that allow us keeping AppRun statically linked.

Regarding Alpine, I would love to also support it I'm just have been a bit busy with the above changes. Your help will be really appreciated.

**Comment by azubieta** [comment]
Forgot to mention that AppImage are always mounted as readonly by design, so I don't think that would be the way to go.

**Comment by AlexTMjugador** [comment]
Thank you for the quick summary of the libc-related changes. It was useful to understand the rationale behind them :smile: 

About getting the glibc version, indeed there barely are any elegant ways that strictly meet your requirements. However, I'm thinking of running the ELF dynamic link interpreter binary directly, which is part of glibc, with the `--version` command line switch. I know that parsing command output was not desired in that StackOverflow question you linked to, but it's worth mentioning that, since this command line switch was introduced two years ago, its format was not changed at all. It also is part of the upstream glibc code, so any modern distro should support it; see this [git blame](https://github.com/bminor/glibc/blame/b92a49359f33a461db080a33940d73f47c756126/elf/dl-usage.c#L43) for the relevant source code and change history. Parsing the first line to extract the version string is also easy, not requiring regexes or anything complex like that.

According to the seemingly distro-agnostic [`man 8 ld.so`](https://man7.org/linux/man-pages/man8/ld.so.8.html), this file should be at `/lib/ld-linux.so.2` for systems with glibc 2.xx. On my personal x64 Debian unstable environment I get the following output (note the glibc version at the end of the first line):

```
$ /lib/ld-linux.so.2 --version
ld.so (Debian GLIBC 2.33-7) release release version 2.33.
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
```

For compatibility with other distros or environments that do not have the interpreter or a symlink to it at `/lib/ld-linux.so.2`, it seems feasible to hardcode additional common interpreter binary locations. If the interpreter is not found at any of these locations, does not support `--version`, or generates unexpected output, it sounds reasonable to assume that the system glibc version is unknown and the compat glibc should be used.

> Forgot to mention that AppImage are always mounted as readonly by design, so I don't think that would be the way to go.

I understand that while executing the AppRun the mount should be read-only, as that indeed does help catching problems. However, to me it sounds like it could be a good idea to add a `preparation-command` key to the recipe schema, mounting the volume read-write during its execution to allow it to do filesystem changes. When that command completes, the volume could, at least theoretically (I didn't look into whether this is really feasible), be remounted read-only, and the AppRun test command executed.

This way users can slightly tweak the Docker image they are using to their needs, while the AppRun still runs as it should in a read-only mount. The alternative is to bring your own Docker images, but that's clumsier, and for some reason uploading images to Docker Hub takes ages for me, not even remotely taking advantage of my available upload bandwidth.

**Comment by azubieta** [comment]
I'm running KDE Neon based on Ubuntu focal which ships glibc 2.31 and the `--version` argument is not there yet. Therefore to adopt this approach we will have to wait for a few years :(

**Comment by azubieta** [comment]
By the way regarding the issue title, will a `before_command` script be useful to you?

**Comment by AlexTMjugador** [comment]
Yes, that command would be pretty useful!

> Therefore to adopt this approach we will have to wait for a few years :(

If for AppImage purposes is enough to roughly classify between unknown or <= 2.33 glibc, and then precisely between >= 2.33 glibc, it could work today too. Most applications nowadays probably target glibc 2.28 or 2.31, so, if the system glibc is <= 2.33, then we don't lose much by using the bundled glibc, even if it's slightly older than what might be present in the system. Eventually, as distros update glibc, AppImages will start using the newer system glibc! :tada:

**Comment by AlexTMjugador** [comment]
I got around to trying the `before_command` in v1.1.0, and I'm afraid to announce that it didn't solve the need stated in the issue because the container filesystem is still read-only during `before_command`.

**Comment by azubieta** [comment]
@AlexTMjugador Notice that you can extend the existent docker recipes and make the modification you need. This would make you test cases faster.
