### ISSUE TITLE
Allow passing options to appimagetool

### ISSUE THREAD

**Issue by richardg867** [AppImageCrafters/appimage-builder#219]
I maintain the AppImage build infrastructure for a project which just adopted an AppStream metadata file. This file contains some data that isn't 100% valid, and therefore `appimagetool` fails with a complaint that it couldn't validate AppStream metadata. While `appimagetool` provides the `-n` switch to disable AppStream metadata validation, there appears to be no (proper) way to add that option when `appimagetool` is called by `appimage-builder`.

There should be a recipe directive or some other method for passing options to `appimagetool`. Right now, I use a nasty hack where `file_name` is set to `-n`, then the resulting AppImage file is renamed manually by the script that invokes `appimage-builder`.

**Comment by azubieta** [comment]
Latest (continuous builds or master) appimage-builder already set the feature you require by default.
The use of `appimagetool` will replaced in the near future by a python only implementation.
