### ISSUE TITLE
Inconsistent usage of appimagetool in release distributations

### ISSUE THREAD

**Issue by mschuckmann** [AppImageCrafters/appimage-builder#223]
I've run into a problem where the continuous version of appimagetool-x86_64.AppImage (built  Apr 03, 2022) is causing my appimage to crash with the error: `APPRUN_ERROR: Bad address` (I'll be creating an issue in appimagetool for this problem). 

I had a manual install of appimage-builder but I noticed that this project recently released v1.0.0 as a pre-built appimage. 
So downloaded that and tried it and I get the same error. 

- I did a little digging and I can see that for the v1.0.0 tag of AppImage-builder there is the recipes/AppImageBuilder.yaml file which I assume is what is used to build the prebuilt appimage. That file references the continuous version of appimagetool-x86_64.AppImage (this seems like bad practice to me). 
- I can also see that the Dockerfile,which is how I assume you create the Docker image, it references version 13 of appimagetool-x86_64.AppImage, that seems like good practice but is inconsistent with the pre-built appimage. 

It seems that release version of appimage-builder should be consistent from one distribution method to another and it should probably reference released software not pre-release software that is likely to change from build to build and to have bugs.

**Comment by azubieta** [comment]
@mschuckmann you are right in your claims. I'm also planning to drop the dependency on appimagetool as their functionalities can be reproduced easily by builder itself.

**Comment by azubieta** [comment]
Fixed, the appimage-builder bundle ships appimagetool 13 now.

**Comment by mschuckmann** [comment]
Great, does that mean you'll be releasing a new v1.0.1 release? 

BTW, we've been having trouble with our app-images crashing with the following error `APPRUN_ERROR: Bad address`
This started occurring a couple of weeks ago when we rebuilt our build server docker image with changes unrelated to appimage-builder.  We reverted to an older version of our docker image to get around the problem for now. 
I did a little experimentation with the v1.0.0 appimage-builder pre-built appimage but the problem seemed to persist. 

I've been meaning to create issue for the problem but I haven't had time to create a minimally reproducible example yet. Has anyone else reported similar problems.

**Comment by azubieta** [comment]
> Great, does that mean you'll be releasing a new v1.0.1 release?

I already did :)

> I've been meaning to create issue for the problem

yes please, I'll take care ASAP. So far this is the first report I have received  any similar reports so I'll waiting for yours.

**Comment by azubieta** [comment]
> So we figured out at least part of our problem, our yaml recipe files had the runtime version set to release "1.2.5"

It seems that I still have many moving parts to fix. Sorry about that, will add a big fat error to notice people that appimabe-builder 1 requires AppRun v2.

> So I'm left with the conundrum of do I explicitly set the runtime version in my yaml

If you already have a working recipe please fix runtime version on the recipe and the appimage-builder version on your script so I would not break it again.

**Comment by mschuckmann** [comment]
Thanks for the quick response and an error is probably a good idea.

**Comment by azubieta** [comment]
Just for reference, in this commit was added the error notification: https://github.com/AppImageCrafters/appimage-builder/commit/647b5914dd0db71739d12ce4987f1e732726818d

**Comment by mschuckmann** [comment]
@azubieta I just downloaded v1.0.2 of the appimage-builder pre-built AppImage and I noticed that you now support a `--version` option which is fantastic. However I noticed that is using the "continuous" version of appimagetool. 

```
$ /tmp/appimage-builder --version
appimage-builder: 1.0.2
appimagetool, continuous build (commit 8bbf694), build <local dev build> built on 2020-12-31 11:48:33 UTC
```
Is this intentional?

**Comment by azubieta** [comment]
@mschuckmann appimagetool have received several updates since the latest release was made and those are in much need. That's why we use continuous hopefully we will replace appimagetool in the near future (working on it right now).

**Comment by mschuckmann** [comment]
@azubieta so it sounds like you've reversed course from your statement a few days ago: 

> Fixed, the appimage-builder bundle ships appimagetool 13 now.

Which I suppose is fine as long as your consistent and are relatively confident that the continuous build of appimagetool is free of problems at the time the that you create your release.  I would be a bit concerned that older continuous builds are not saved as released so if a new continuous build of appimagetool occurs you will not be able to rebuild v1.0.2 of appimage-builder.

**Comment by mschuckmann** [comment]
And to the point of consistency it looks like your Dockerfile is pulling appimagetool version 13. 

https://github.com/AppImageCrafters/appimage-builder/blob/dd041050e65f8eff28f878a092fd07bcf3ec5a4d/Dockerfile#L12
