### ISSUE TITLE
libapprun_hooks.so not loaded if the file name contain spaces

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/appimage-builder#23]
```
./'Hello World-latest-x86_64-20200508174314.AppImage' 
ERROR: ld.so: object '/tmp/.mount_Hello' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'BhKsJS/libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

**Comment by alex-tee** [comment]
I started getting this in my latest builds (not sure since when)
I haven't changed anything so I think it's appimage-builder causing it

**Comment by azubieta** [comment]
@alex-tee could you share a broken AppImage to inspect it?

I did a big refactor from v0.8 to v0.9 so I may had broken something :sweat:

**Comment by alex-tee** [comment]
hmm looks fixed on the latest build www.zrythm.org/downloads/zrythm-1.0.0.alpha.19.0.1.r9.ge66b59e9d-x86_64(1).AppImage

the error was happening on my previous build, which is also missing some libs: www.zrythm.org/downloads/zrythm-1.0.0.alpha.19.0.1.r9.ge66b59e9d-x86_64.AppImage

if you get an error on the 2nd one that libserd etc. are missing you can install liblilv-dev to make it go away

**Comment by azubieta** [comment]
No issues here. Let's close the issue. Feel free to reopen if required.

**Comment by tomekit** [comment]
We're also getting this: `2024/04/29 22:11:30 mount helper error: ERROR: ld.so: object 'libapprun_hooks.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.` when starting FUSE mount, however at this stage we haven't identified what functionality doesn't work because of that.
