### ISSUE TITLE
mksquashfs `-quiet` is only supported in very recent versions

### ISSUE THREAD

**Issue by twizmwazin** [AppImageCrafters/appimage-builder#244]
We use Ubuntu 18.04 for building an appimage, and after upgrading to version 1.0.3, the build is now failing due to `-quiet` being unsupported. Ubuntu 18.04 uses squashfs-tools 4.3, `-quiet` was introduced in 4.4. Can this change be reverted to better compatibility with older versions?

The problematic change looks to be d15848bb7753f30450b0eade2bdbc5878bd17a6b, introduced on line 84.

**Comment by azubieta** [comment]
Fix pushed, will make another release by the end of the week.
