### ISSUE TITLE
font's not being loaded in the Archlinux docker image

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/appimage-builder#25]
Fonts support on the testing archlinux docker image is broken.

I'm not familiar with Arch, therefore I may need some help on this. You can find the image recipe here: https://github.com/AppImageCrafters/tests-env/blob/master/archlinux-latest.docker

**Comment by probonopd** [comment]
Maybe it's just me, but what is the actual problem? Can you share a screenshot?

**Comment by azubieta** [comment]
NOT WORKING FONTS:
![Screenshot_20200531_125958](https://user-images.githubusercontent.com/1138094/83359241-a92fbf80-a33e-11ea-99b6-5a181705a9fd.png)

WORKING FONTS:
![Screenshot_20200531_130023](https://user-images.githubusercontent.com/1138094/83359252-b482eb00-a33e-11ea-92ad-5907d11bf6e8.png)

**Comment by probonopd** [comment]
Uh, that's not even square boxes... never seen that.

**Comment by azubieta** [comment]
There were no fonts installed in the container. It should be fixed now.
