### ISSUE TITLE
is the file AppImageBuilder.yml   must existed before create appimage?

### ISSUE THREAD

**Issue by xiaoyifang** [AppImageCrafters/appimage-builder#259]
as title.

If it must exist ,how to make it work with github action which need no manual interaction.

**Comment by azubieta** [comment]
Yes, the `AppImageBuilder.yml` is the recipe and contains the instructions for creating the AppImage. To use it with github action you need include it in your repository and call `appimage-builder --skip-tests --recipe <AppImageBuilder.yml path>`
