### ISSUE TITLE
appimage-builder fails while executing tests using the tutorial example

### ISSUE THREAD

**Issue by zocker-160** [AppImageCrafters/appimage-builder#27]
I'm trying to learn how to create an appimage and I started to with the official tutorial I found here:

https://appimage-builder.readthedocs.io/en/latest/intro/tutorial.html

Sadly I get an error when trying to create the Appimage in the last step:
```
INFO:TEST CASE 'fedora':Executing: ./AppRun
ERROR:appimage-builder:Tests failed
ERROR:appimage-builder:Execution failed. Error message: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```

log file and yml recipe attached (I renamed the yml to txt, because GitHub doesn't accept .yml files)
[appimage builder-log.txt](https://github.com/AppImageCrafters/appimage-builder/files/4832265/appimage.builder-log.txt)
[AppImageBuilder.yml.txt](https://github.com/AppImageCrafters/appimage-builder/files/4832269/AppImageBuilder.yml.txt)

Is this a bug, or did I do something wrong?

**Comment by azubieta** [comment]
From the logs I can see that the AppRun binaries were not downloaded. A few questions:
- how are you installing appimage-builder ?
- how are you running appimage-builder ?
- is the AppDir folder writable (provably it's, just double check)?

**Comment by zocker-160** [comment]
> how are you installing appimage-builder ?

I installed it using pip via `pip3 install appimage-builder` like it is written [here](https://appimage-builder.readthedocs.io/en/latest/intro/install.html#intro-install)

> how are you running appimage-builder ?

I run it from the terminal and call `appimage-builder` from the same folder where the AppDir is located

> is the AppDir folder writable (provably it's, just double check)?

I did a `chmod -R 777` and same error :-(

It is running in a VM, so maybe that might be a problem?

**Comment by azubieta** [comment]
Can you try installing it using `sudo pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git`

Is docker installed in the VM?

**Comment by azubieta** [comment]
The tutorial is also recorded here: https://www.youtube.com/watch?v=2OO3KY6dWVU

**Comment by zocker-160** [comment]
> Can you try installing it using sudo pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git

I get a different error now:
```
INFO:root:Writing bundle info to: .bundle.yml
INFO:root:============
INFO:root:AppDir tests
INFO:root:============
INFO:root:
INFO:root:Running test: debian
INFO:root:-----------------------------
INFO:TEST CASE 'debian':Executing: ./AppRun
INFO:TEST CASE 'debian':Aborted
ERROR:appimage-builder:Tests failed
ERROR:appimage-builder:None
```

> Is docker installed in the VM?

yes it is

also I actually followed the video on my first try...... maybe I am missing some dependencies or doing something completely wrong :-(

**Comment by azubieta** [comment]
Can you run docker from your current user without sudo?

Here you can find how to do it: https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo?answertab=votes#tab-top

Maybe that is what's happening

**Comment by zocker-160** [comment]
@azubieta I found the issue!

The problem was disk space, because the script is downloading docker containers worth of over 4GB total.....

![Screenshot_20200625_202013](https://user-images.githubusercontent.com/36563538/85776741-481ec000-b721-11ea-92be-8084427c94b9.png)

I increased the drive size and it's working now.

Sorry for bothering and thank you for the help, this was totally my fault.

**Comment by azubieta** [comment]
Don't worry we are here to help. Those docker images are indeed quite big. They contain complete functional systems in order to properly test the resulting binaries.

It would be great to optimize them but some expertise on configuring each system is required.
