### ISSUE TITLE
APPRUN_ERROR: No such file or directory

### ISSUE THREAD

**Issue by carlonluca** [AppImageCrafters/appimage-builder#272]
I'm having a problem very similar to #148; when running the appimage I get:

`APPRUN_ERROR: No such file or directory`

The problem only appears on arm64, the x64 appimage works properly. As said in #148, I mounted the appimage and this is what I see in the env file:

`APPDIR_EXEC_PATH=$APPDIR/usr/bin/procweb-qt`

and in fact it is there:

```
file usr/bin/procweb-qt
usr/bin/procweb-qt: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter lib/ld-linux-aarch64.so.1, BuildID[sha1]=5570c8568939fa5570ecf5ede3982e7b88d28867, for GNU/Linux 3.7.0, not stripped
```

Is the relative path for the interpreter correct? Can this be caused by a missing dependency?

This is the first time I use appimage-builder, so I do not fully understand how it works yet. My project is however open source, so this is the recipe I built: https://github.com/carlonluca/procweb/blob/master/appimage-builder/AppImageBuilder_aarch64.yml.

Any idea how I could debug further? Thanks!

**Comment by goldstar611** [comment]
I noticed in your x64 yml you have `deb [arch=amd64] http://` in the source lines. If you change 
`deb http://`
to
`deb [arch=arm64] http://`

does that help? I wonder if non-arm64 binaries are inside the appimage.

**Comment by goldstar611** [comment]
I had a quick moment to run the AppImageBuilder tool against  your yml file (but not enough time to compile your project). Assuming your project is compiled correctly, I can see one large issue with the architecture of `AppRun`, which appears to be x86_64:

`~/Desktop/UntitledFolder/AppDir $ find . -type f -executable -exec file {} \;`
```
...
./AppRun: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=b33b58c29edac92944e344dc47324f896ae2f3fe, not stripped
```

**Comment by carlonluca** [comment]
Hello,
if I mount my appimage I get:

```
/tmp/.mount_procwe7C6j7n $ file AppRun
AppRun: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=db3c30272ec045e00c179e753dda3fb03ad699f7, not stripped
```

by running the same command you used I can only see aarch64 libraries. I can make it explicit to use arm64 repos, but libs installed from the repos seem to be for the aarch64 arch.

**Comment by goldstar611** [comment]
How about if you use the `strace` program to see which file is attempting to be accessed that produces the ENOENT (not found) error. This would be my next step.

**Comment by carlonluca** [comment]
Unfortunately I did that but I did not get much more info:

```
chdir("/tmp/.mount_procwengdYOC/runtime/compat") = 0
execve("/tmp/.mount_procwengdYOC/usr/bin/procweb-qt", ["/tmp/.mount_procwengdYOC/usr/bin"...], 0x394e2af0 /* 71 vars */) = -1 ENOENT (No such file or directory)
write(2, "APPRUN_ERROR: No such file or di"..., 39APPRUN_ERROR: No such file or directory) = 39
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by carlonluca** [comment]
It is probably something done to the binary by appimage-builder itself. When I copy the binary into the AppDir directory and aèèimage-builder is executed, the md5 of the binary changes. The new binary has the same behavior also in the host:

```
# AppDir/usr/bin/procweb-qt 
bash: AppDir/usr/bin/procweb-qt: No such file or directory
```

**Comment by JohnXLivingston** [comment]
As mentionned by @carlonluca , it seems to be the same issue than https://github.com/AppImageCrafters/appimage-builder/issues/278
In https://github.com/AppImageCrafters/appimage-builder/issues/278 , the problem occurs using an official documented config file (bash AppImage), by just replacing the repository: amd64 => aarch64.

**Comment by goldstar611** [comment]
```
<       [Requesting program interpreter: /lib/ld-linux-aarch64.so.1]
                                         ^
---
>       [Requesting program interpreter: lib/ld-linux-aarch64.so.1]
                                         ^
```
I wonder if this is an "off by one" error or intentional. I can understand the reasoning for using a relative path to ld-linux but it seems suspicious to me. 

Does the resulting AppDir have a `lib/-linux-aarch64.so.1` in it?

**Comment by carlonluca** [comment]
Yes, I noticed that, but I suspect that is expected. This is inside the AppDir:

```
./AppDir/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1
./AppDir/lib/ld-linux-aarch64.so.1
./AppDir/runtime/default/lib/ld-linux-aarch64.so.1
```

and also it seems on x64 the change is identical:

```
<       [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
---
>       [Requesting program interpreter: lib64/ld-linux-x86-64.so.2]
```

Missing init and data section is also suspect.

**Comment by goldstar611** [comment]
Are the sections actually missing or did the names get stripped? I'm not familiar with either ELF format basics or stripping of ELF files.

**Comment by carlonluca** [comment]
Unfortunately I do not have an answer to this. I guess the names are stripped, not sure if this is a problem or not. However, the fact that the binary cannot be executed seems to suggest there is a problem very early in the process.
