### ISSUE TITLE
AppRunError: Unable to find a wrapper for: ELF 64-bit LSB pie , x86-64

### ISSUE THREAD

**Issue by realmazharhussain** [AppImageCrafters/appimage-builder#29]
I am compiling gdm3setup's last version from master branch as appimage and it is giving me the following error

AppImageBuilder.app_dir.runtimes.wrapper.app_run.AppRunError: Unable to find a wrapper for: ELF 64-bit LSB pie , x86-64

Am I missing something?

**Comment by azubieta** [comment]
appimage-builder is trying to find the right wrapper binary for your app but it's failing because it's built using `-fpie`.

This is a bug, appimage-builder should use the `x86_64` AppRun binary.

Right now is quite late for me so I'll address it tomorrow. If you are in a hurry you can check: https://github.com/AppImageCrafters/appimage-builder/blob/de6fe58e5f47236a007ef76820cdc5acd9d6acee/AppImageBuilder/app_dir/runtimes/wrapper/app_run.py#L124 and send a patch.

**Comment by realmazharhussain** [comment]
Thanks for reply. I am no developer. I cannot send a patch nor am I in a
hurry.
I'll wait for a patch from you.

Thanks again for your help.

**Comment by azubieta** [comment]
@realmazharhussain  Would you mind to re-test using the code from branch: fix_unable_to_find_wrapper_29 ?

Use the command below to install it:
`pip install git+https://github.com/AppImageCrafters/appimage-builder.git@fix_unable_to_find_wrapper_29`

**Comment by realmazharhussain** [comment]
Of Course.

**Comment by realmazharhussain** [comment]
What python version (2 || 3)  does appimage-builder need? Because I think I am using version 3 of python.

**Comment by realmazharhussain** [comment]
Sorry to bother you. gdm3setup does not run because it is very old (2013-14). But I will try appimage-builder on another app. 

One thing I want in your app is the ability to utilize package info already available in apt database. It downloads over 100MB of data from distro servers just to get a list of available packages. I don't like that behavior. But it's a very good app by the way. I thank you for making this app.

**Comment by azubieta** [comment]
I have packaged other vary old applications before. My recommendation is to use a ubuntu/debian repository from the same time, so it can pull all the right dependencies.

We used the packages available in the system, but we stop doing it to allow cross-packaging. By example, you can create an armrf AppImage from a x86_86 system.

**Comment by realmazharhussain** [comment]
Thanks.
I'll try again.

**Comment by realmazharhussain** [comment]
Bro, I have other errors now. I am creating a new issue.

**Comment by azubieta** [comment]
I tested this on a Debian buster system and works ok. Please reopen if the problem persist.
