### ISSUE TITLE
Question: " before_runtime" and "after_runtime"

### ISSUE THREAD

**Issue by eposscot** [AppImageCrafters/appimage-builder#295]
In the documentation

---
Section scripts

It’s possible to insert scripts before and after the bundle and runtime steps. Those can be used to perform additional tweaks to the AppDir before proceeding with the tests.

The allowed keys are:

    before_bundle
    after_bundle
    before_runtime
    after_runtime
---

Is the before_runtime is a custom script that is actioned when the user runs the App Image and the script is executed just before the application and  after_runtime is the script that is actioned after the main application has been executed?

Or, is this only related to generating the AppImage it self.

Apologies for asking, just the documentation is not very clear. 

Thanks

John

**Comment by goldstar611** [comment]
In my experience those hooks are only executed during the appimage build. I think before_bundle was before `apt-get install` and before_runtime was before the libc stuff was added (or something like that). I was also looking to hook into when the user executes the application but figured I could accomplish this by just setting the start up application to a custom script.
