### ISSUE TITLE
"UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte" on "Debian BullsEye"

### ISSUE THREAD

**Issue by realmazharhussain** [AppImageCrafters/appimage-builder#32]
Well, I have been trying to use appimage-builder to build an appimage, but the problem is, it does not check for its own dependencies before running commands. It uses 200+ MBs of data using apt-get update and apt-get download. After it has downloaded files, it deploys these packages and goes on to running some other code or commands. But what does it find? Some file or module is not present in the system or some package is not installed. So I install a package with those files in it. In theory, it should work now. But when I run appimage-builder again, it shows the following message:
**UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 0: invalid start byte**
Then I have to delete appimage-builder-chache directory to start from beginning. it runs apt-get commands again and then it finds something else to be missing. So, I have to do the same process again and again without any meaningful result. I did it almost 7-8 times before I gave up. I'm sick of this behaviour of your app. It should just check for dependencies before doing anything else and tell me what package/file/module is missing in the beginning. And if I forget to install something, it should be able to continue after I install that thing.
I am using Debian BullsEye with gnome desktop by the way.

**Comment by azubieta** [comment]
It's a bit complicated to detect all the dependencies before making the AppDir. It may be required to run certain tools depending on what components get deployed into the bundle. Anyway, I'll do my best to improve this as much as possible.

 Regarding the error, I'll set up a VM to reproduce your issue.

**Comment by azubieta** [comment]
I just tested building the examples at https://github.com/AppImageCrafters/appimage-builder/tree/master/examples

And the AppImages were created without issue. Would you please describe what kind of app are you trying to pack? Would you also share your AppImageBuilder.yml, if possible?

**Comment by azubieta** [comment]
Closing it due inactivity. Please reopen if required.
