### ISSUE TITLE
Icon design

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/appimage-builder#33]
Please @UriHerrera bless appimage-builder with a shiny icon :)

**Comment by Lvaskz** [comment]
Puede cualquiera contribuir aquí?

**Comment by Lvaskz** [comment]
do you have some icon already ?

**Comment by azubieta** [comment]
@Lvaskz 

> Puede cualquiera contribuir aquí?

si

> do you have some icon already ?

yes, but we don't like it
https://avatars.githubusercontent.com/u/50029923?s=200&v=4

**Comment by Lvaskz** [comment]
Ya veo, estuve involucrado en el diseño del primer icono de appimagelauncher hasta que consiguieron otro. Tal vez podría intentar proponer algunos. Tienes algunas ideas? O simplemente puedo ser creativo ? De todas maneras vas ha escoger.
Tienen algún elemento dentro de la imagen arriba que quieran preservar?

**Comment by azubieta** [comment]
Yo tenia la idea de combinar un icono de terminal de algún tema iconos existente con el de AppImage, especificamente quería conservar la flecha y el engrane. Fuera de eso puedes ser creativo

**Comment by Lvaskz** [comment]
De acuerdo, voy a empezar a pensar y cuando tenga algún avance te lo
presento. 👍🎉

**Comment by Lvaskz** [comment]
![g1340](https://user-images.githubusercontent.com/29207169/112199667-00f02d80-8bd4-11eb-90c6-762927f56f00.png)

**Comment by Lvaskz** [comment]
![g1353](https://user-images.githubusercontent.com/29207169/112199695-09486880-8bd4-11eb-89d5-5573d2e695cf.png)

**Comment by Lvaskz** [comment]
Algunos bosquejos, nada definitivo.
Qué opinas?

**Comment by Lvaskz** [comment]
![g1091](https://user-images.githubusercontent.com/29207169/112220877-5d5f4700-8bec-11eb-9cc9-b50a9c55b865.png)

**Comment by azubieta** [comment]
El del brazo robótico como que tienes muchas veces el símbolo, jejeje.
Aunque me gustaría que el icono esté más relacionado al software. Este era el que te decía que había hecho para otra app
https://cdn.pling.com/cache/85x85-crop/img/1/4/3/9/3cee73bb3120604e76fd731e0ec19c2a38b1de69e2bc9f1d1bda1e00869548e43c98.png

**Comment by Lvaskz** [comment]
> Aunque me gustaría que el icono esté más relacionado al software. Este era el que te decía que había hecho para otra app
> https://cdn.pling.com/cache/85x85-crop/img/1/4/3/9/3cee73bb3120604e76fd731e0ec19c2a38b1de69e2bc9f1d1bda1e00869548e43c98.png

Ah Ok. Pero por qué no usas ese? No se ve mal

**Comment by Lvaskz** [comment]
Me refiero a este https://cdn.pling.com/cache/85x85-crop/img/1/4/3/9/3cee73bb3120604e76fd731e0ec19c2a38b1de69e2bc9f1d1bda1e00869548e43c98.png

**Comment by UriHerrera** [comment]
![bitmap](https://user-images.githubusercontent.com/3053525/112227112-b7640a80-8bf4-11eb-8d72-6f2d8a6cf61d.png)


@azubieta Here's an icon.

**Comment by azubieta** [comment]
@UriHerrera that looks great, do you have it in svg ?

**Comment by Lvaskz** [comment]
> ![bitmap](https://user-images.githubusercontent.com/3053525/112227225-ee3a2080-8bf4-11eb-965a-66e9ef936285.png)
> 
> @azubieta Here's an icon.

Yes it looks great!!
