### ISSUE TITLE
AppImageBuilder.script.ExecutionFailed (exited with code 2)

### ISSUE THREAD

**Issue by CineEncoder** [AppImageCrafters/appimage-builder#34]
Hi,
My project: https://github.com/CineEncoder/cine-encoder
When trying to create an Appimage the following error occurs:

```
[helg@Houston Appimage]$ appimage-builder --recipe appimage-builder.yml --skip-test
INFO:script: + rm -rf AppDir  | true
INFO:script: + mkdir -p AppDir/usr/src
INFO:script: + cp main.py  AppDir/usr/src -r
INFO:script: + python3 -m pip install --system --ignore-installed --prefix=/usr --root=AppDir -r ./requirements.txt
WARNING:script: 
WARNING:script: Usage:   
WARNING:script:   /usr/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
WARNING:script:   /usr/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
WARNING:script:   /usr/bin/python3 -m pip install [options] [-e] <vcs project url> ...
WARNING:script:   /usr/bin/python3 -m pip install [options] [-e] <local project path> ...
WARNING:script:   /usr/bin/python3 -m pip install [options] <archive url/path> ...
WARNING:script: 
WARNING:script: no such option: --system
Traceback (most recent call last):
  File "/usr/bin/appimage-builder", line 18, in <module>
    __main__();
  File "/usr/lib/python3.8/site-packages/AppImageBuilder/__main__.py", line 59, in __main__
    script.execute()
  File "/usr/lib/python3.8/site-packages/AppImageBuilder/script.py", line 39, in execute
    raise ExecutionFailed("%s exited with code %s" % (instruction, command.return_code))
AppImageBuilder.script.ExecutionFailed: python3 -m pip install --system --ignore-installed --prefix=/usr --root=AppDir -r ./requirements.txt exited with code 2
```
appimage-builder.yml (https://github.com/CineEncoder/cine-encoder/blob/master/appimage-builder.yml)
requirements.txt (https://github.com/CineEncoder/cine-encoder/blob/master/requirements.txt)

Please tell me what it can be?
(I need help!!!)

**Comment by azubieta** [comment]
Hi!
This is an issue with pip, it seems that the version you are using doesn't support the `--system` argument. Just remove it from your pip call:
`python3 -m pip install  --ignore-installed --prefix=/usr --root=AppDir -r ./requirements.txt`

**Comment by CineEncoder** [comment]
This helped, but another error appeared:

```
WARNING:script: ERROR: Could not find a version that satisfies the requirement ffmpeg-4.2.4 (from -r ./requirements.txt (line 1)) (from versions: none)
WARNING:script: ERROR: No matching distribution found for ffmpeg-4.2.4 (from -r ./requirements.txt (line 1))
```
(But if I remove the ffmpeg version, then the ffmpeg-1.4 version is installed, which is very outdated.)

**Comment by azubieta** [comment]
Those are still pip related issues. 
I'm not a pip expert, I suspect that pip is not downloading the dependencies right. You can try running appimage-builder from a virtualenv whit a good pip setup. Try installing those package manually then run appimage-builder.

Notice that it's recommended to use Ubuntu 18.04 or 20.04 for better results.
