### ISSUE TITLE
gdk-pixbuf-query-loaders not found in Debian 10.5 and Ubuntu focal

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/appimage-builder#36]
`gdk-pixbuf-query-loaders` binary was usually installed into `/usr/bin` this is no longer valid for Debian 10.5 and Ubuntu focal. 
Therefore we need to improve the lookup method.

**Comment by grimmy** [comment]
Just ran into this as well, wondering if anyone has any workarounds?  In the mean time I'm going to build using buster instead but would prefer to build against bullseye.

**Comment by grimmy** [comment]
Did some more digging and ran across https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907306.  I fixed my local builds by creating a symlink to the new location `ln -sf /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders  /usr/bin/gdk-pixbuf-query-loaders`.

**Comment by azubieta** [comment]
@grimmy it used to be part of libgdk-pixbuf2.0-dev but for some reason it's no longer there. You could also add `gdk-pixbuf-query-loaders` dir path to the PATH environment variable with:

`export PATH=/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/:$PATH`

**Comment by trollixx** [comment]
Just ran into this. Probably `appimage-builder` should be aware of where to look for `gdk-pixbuf-query-loaders`?
