### ISSUE TITLE
Qt Application searches plugins in host system and refuses to run

### ISSUE THREAD

**Issue by stsichler** [AppImageCrafters/appimage-builder#37]
When I bundled an AppImage depending on Qt 5.12.8 (Ubuntu 20.04), the resulting image did not run on an older system (Ubuntu 18.04), because Qt still tried to load plugin libraries from the system path /usr/lib/x86_64-linux-gnu/qt5/plugins although appimage-builder v0.6.0 created a qt.conf correctly overriding the plugin path.

The resulting error is:
"Cannot mix incompatible Qt library (version 0x50905) with this library (version 0x50c08)."
and execution stops right after LD_DEBUG=libs showed loading of /usr/lib/x86_64-linux-gnu/qt5/plugins/styles/libqgtk2style.so.

The contents of qt.conf in AppDir/usr/bin/ is:

[Paths]
Prefix=../..
Settings=../../etc
Libraries=usr/lib/x86_64-linux-gnu
Plugins=usr/lib/x86_64-linux-gnu/qt5/plugins

(btw. I suppose that Settings=../../etc should read Setting=etc ??? but that does not influence this bug)

**Comment by azubieta** [comment]
@stsichler as you noted this issue was introduced with the path mapping feature and it's reported at https://github.com/AppImageCrafters/AppRun/issues/14 I'll be working on it and keep you posted. 

In the mean time you can use the path mappings to workaround this. Add a mapping like this:
`/usr/lib/x86_64-linux-gnu/qt5/:$APPDIR/usr/lib/x86_64-linux-gnu/qt5/`

**Comment by stsichler** [comment]
Ok, sorry, I was not aware of that being related to the new path mapping feature.

When I introduce a mapping like you proposed, the library loading works, but the application crashes right at start, even on the system that created the AppImage. 

gdb show this:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7dc41e6 in redirect_path_full () from /tmp/.mount_LogVieL3EouI/usr/lib/x86_64-linux-gnu/libapprun_hooks.so

**Comment by azubieta** [comment]
@stsichler that looks like a nasty bug, please fill and issue at: https://github.com/AppImageCrafters/AppRun/issues
and attach the AppDir zipped, so I can give it a try and make a quick bugfix.

**Comment by stsichler** [comment]
see https://github.com/AppImageCrafters/AppRun/issues/15

**Comment by azubieta** [comment]
@stsichler after checking your yml file I found that the path mapping was wrong. It should be something like:

`/usr/lib/x86_64-linux-gnu/qt5:$APPDIR/usr/lib/x86_64-linux-gnu/qt5`

I change this and the app runs properly.

I will add better checks to appimage-builder and to the runtime.

**Comment by stsichler** [comment]
Ok, fixing the directory mapping syntax in AppImageBuilder.yml causes the AppImage to run again on the system it was created, but it still doesn't solve the Qt plugin loading problems on the 18.04 Ubuntu for me.

**Comment by azubieta** [comment]
I have pushed a fix for the issue with the `qt.conf` not being found. Now it should be possible to make your AppImage without the path mappings. 

Regarding the plugins that are still being loaded from your system. Please make sure they are being bundled.

**Comment by stsichler** [comment]
I can confirm that v0.6.1 fixes the problem for me.
THANK YOU!!!

btw. it's a very cool project :)

**Comment by azubieta** [comment]
Awesome! It's a pleasure to serve :)
