### ISSUE TITLE
Docker build stopped to work for me

### ISSUE THREAD

**Issue by akontsevich** [AppImageCrafters/appimage-builder#51]
Docker build stopped to work for me for some reason, still works for other colleagues. Any ideas? Error is following: 

https://appimage-builder.readthedocs.io/en/latest/intro/install.html#install-in-a-docker-container

> 2020-10-20 12:35:11 (98.1 KB/s) - '/opt/appimagetool' saved [2113576/2113576]
> 
> /bin/sh: 1: /opt/appimagetool: not found
> The command '/bin/sh -c wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /opt/appimagetool     && chmod +x /opt/appimagetool     && cd /opt/; /opt/appimagetool --appimage-extract     && mv /opt/squashfs-root /opt/appimagetool.AppDir     && ln -s /opt/appimagetool.AppDir/AppRun /usr/local/bin/appimagetool     && pip3 install appimage-builder' returned a non-zero code: 127

Related to this PR: https://github.com/airmap/qgroundcontrol/pull/1#

**Comment by akontsevich** [comment]
```
# chmod +x /opt/appimagetool
# cd /opt/;
# /opt/appimagetool --appimage-extract
bash: /opt/appimagetool: No such file or directory
# ls
appimagetool
```
which is weird.

**Comment by azubieta** [comment]
Can you verify if wget is downloading the file properly, Github API limits may be affecting you.

**Comment by akontsevich** [comment]
> Can you verify if wget is downloading the file properly, Github API limits may be affecting you.

How? According to messages in console - downloaded fine.

**Comment by akontsevich** [comment]
Seems same problem was here: https://github.com/AppImage/pkg2appimage/issues/373
However solution is not clear to me.

**Comment by azubieta** [comment]
That's used to run the AppImage without extracting it. In the script you're running the AppImage is extracted before attempting to use it. This is done precisely to work around the docker issue. I've tried your script locally and it works as expected.

> However solution is not clear to me.

They are removing the AppImage magic bytes, those are set (by desing) in a wrong position and some interpreters fail to understand it.

**Comment by akontsevich** [comment]
Yeah, this hack helped: https://github.com/AppImage/pkg2appimage/issues/373#issuecomment-495754112  - add it to Your doc here:  [install-in-a-docker-container](https://appimage-builder.readthedocs.io/en/latest/intro/install.html#install-in-a-docker-container), @azubieta.

**Comment by akontsevich** [comment]
> I've tried your script locally and it works as expected.

It also works fine on our CI in docker, however suddenly stopped to work on my local machine.

**Comment by azubieta** [comment]
Done, thanks for the help!

**Comment by azubieta** [comment]
The magic bytes issue should be solved in AppImage v3. When ever that happens.
