### ISSUE TITLE
Libc issue building appimage on archlinux

### ISSUE THREAD

**Issue by mmtrt** [AppImageCrafters/appimage-builder#52]
I know builder doesn't support this os yet I tried to build anyways to test this,

So steps I did to built appimage

* Used pacman to download deps to cache dir

* Unpacked all deps to AppDir

* Used builder recipe without having apt section and added env overrides 

It did built fine but builder did not auto added libc to opt/libc.

if I manually add links of ld-linux* files to opt/libc/usr/lib, lib32 dirs then appimage works on arch only but that doesn't use glibc from appimg.

**Comment by azubieta** [comment]
You can take a look at the packages listed [here](https://github.com/AppImageCrafters/appimage-builder/blob/master/AppImageBuilder/app_dir/bundlers/apt/package_lists.py#L77), and deploy their Arch versions into `opt/libc`.

You may also want to exclude the ones listed in

https://github.com/AppImageCrafters/appimage-builder/blob/master/AppImageBuilder/app_dir/bundlers/apt/package_lists.py#L50

https://github.com/AppImageCrafters/appimage-builder/blob/master/AppImageBuilder/app_dir/bundlers/apt/package_lists.py#L64

Those are too related to the graphics drivers and will cause your app to fail on NVidia system

**Comment by mmtrt** [comment]
Thanks I've made some progress AppImg seems to work but I have another issue app can't seem to find freetype2 library on ubuntu.

**Comment by azubieta** [comment]
Have you tried to also bundle freetype2 ?

You can use strace or the runtime debug mode to see which paths are being tested, and add a path mapping if required.

**Comment by mmtrt** [comment]
yes but appimg works good now though I'm getting this
```
openat(AT_FDCWD, "/tmp/.mount_wine-sN71vXz/usr/lib/tls/haswell/x86_64/libapprun_hooks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/tmp/.mount_wine-sN71vXz/usr/lib/tls/haswell/libapprun_hooks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/tmp/.mount_wine-sN71vXz/usr/lib/tls/x86_64/libapprun_hooks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/tmp/.mount_wine-sN71vXz/usr/lib/tls/libapprun_hooks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/tmp/.mount_wine-sN71vXz/usr/lib/haswell/x86_64/libapprun_hooks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/tmp/.mount_wine-sN71vXz/usr/lib/haswell/libapprun_hooks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/tmp/.mount_wine-sN71vXz/usr/lib/x86_64/libapprun_hooks.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

appimage
[Releases](https://github.com/mmtrt/WINE_AppImage/releases/tag/continuous-arch) | [source](https://github.com/mmtrt/WINE_AppImage/tree/arch)

**Comment by azubieta** [comment]
Great, that error is "harmless". And means that LD_PRELOAD is being set when executing an external app.

I'm already working on it https://github.com/AppImageCrafters/AppRun/issues/21

**Comment by mmtrt** [comment]
Good, I guess can close this issue now.
