### ISSUE TITLE
Produced appimage fails to run on other systems with "File not found" on execve

### ISSUE THREAD

**Issue by josh-richardson** [AppImageCrafters/appimage-builder#57]
Hi,

Further to my previous issue, I've been able to find a workaround. I've currently come upon another problem which is that once the appimage is build & executed on a different system, I get a 'file not found' when attempting to execute the appimage. 

I'm building the appimage on Debian 10, as follows:
`Linux debian-box 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux`

I'm then running the appimage on Manjaro, as follows:
`Linux opus 5.8.18-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020 x86_64 GNU/Linux`

The libc version on the Debian machine is 2.28, on the Manjaro 2.32.

When running the appimage on Debian, the appimage unzips to the tmp directory, and invokes `execve` on the entrypoint binary:
```
execve("/tmp/.mount_AlbertXxV4yQ/usr/bin/albert", ["/tmp/.mount_AlbertXxV4yQ/usr/bin"...], 0xc78090 /* 78 vars */) = 0
```
This is successful and the app runs fine.

However, when the appimage is invoked on Manjaro, I see the following:

```
access("/tmp/appimage-18df7fd4-9f36-42f4-bd98-e571e07249c5-ld-linux-x86-64.so.2", F_OK) = 0
chmod("/tmp/appimage-18df7fd4-9f36-42f4-bd98-e571e07249c5-ld-linux-x86-64.so.2", 0770) = 0
execve("/tmp/.mount_Albert6SehZ0/usr/bin/albert", ["/tmp/.mount_Albert6SehZ0/usr/bin"...], 0x1e01780 /* 114 vars */) = -1 ENOENT (No such file or directory)
```

I'm not entirely sure why this happens, but I suspect it's something to do with not being able to access the correct dynamic linker. I've been able to run the appimage with GDB and break on the `execve` instruction. I can then go into the appimage directory in `/tmp` and look around. It's using the following as its interpreter:
```
/tmp/.mount_Albert7zPPDs/usr/bin/albert: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /tmp/appimage-155e2dab-6729-4b90-bbf3-fda53a4775f1-ld-linux-x86-64.so.2, BuildID[sha1]=9a8a065af8bc1accfca8287621eeb01aea12f5aa, for GNU/Linux 3.2.0, with debug_info, not stripped
```

This file seems not to exist at the moment that the exec occurs, but does seem to exist in the strace. I'm unsure where to go from here, but am wondering if anyone else has hit this.

**Comment by josh-richardson** [comment]
Update, I can confirm that `ld-linux` version that the `albert` in the extracted /tmp directory links to seems to be constant, whereas on each execution the extracted location of the `ld-linux` seems to have a random name. If I break before the execve and rename the file to the one wanted by the extracted executable, everything seems to run fine.

**Comment by azubieta** [comment]
The `ld-linux` path fixed because in the `PD_INTERP` entry cannot be modified (so far) at runtime in elf files. The AppRun is an statically linked executable which doesn't require `ld-linux`. Is this binary the one that detects which `glibc` version is present in the system and decides whether to use it or not.
