### ISSUE TITLE
Add flutter support

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/appimage-builder#70]
Flutter (https://flutter.dev) is a new technology for creating multi platform applications from Google. This issue is meant to explore the possibility of supporting it on appimage-builder.

Questions:
- How to build a flutter application on GNU/Linux?
- What dependencies have a flutter built application on GNU/Linux?

I would be great to have a hello world application that we could use for testing.

**Comment by azubieta** [comment]
Hello @stuartmorgan,
I need some help with some basic topics of Flutter in order to create a recipe for packaging AppImages from Flutter apps. You can find the questions in the issue description.
Thanks

**Comment by stuartmorgan** [comment]
> * How to build a flutter application on GNU/Linux?

https://flutter.dev/desktop

> * What dependencies have a flutter built application on GNU/Linux?

I don't know what level of detail/completeness you are looking for here. The immediate dependencies are the things in the `bundle` subdirectory of the build output.

> I would be great to have a hello world application that we could use for testing.

I'm not sure what you are looking for that's different from the output of `flutter create`.

**Comment by azubieta** [comment]
It seems that nothing special needs to be done to support packing flutter apps. See an example here:

https://github.com/AppImageCrafters/appimage-builder-flutter-example/

**Comment by azubieta** [comment]
Closing this issues a solved! :+1: :partying_face: :confetti_ball:
