### ISSUE TITLE
Package Lookup Failed on Sample Application

### ISSUE THREAD

**Issue by zesoft23** [AppImageCrafters/appimage-builder#74]
Hey folks,

I'm having an issue with creating the app image mentioned in the [Tutorial.](https://appimage-builder.readthedocs.io/en/latest/intro/tutorial.html) I'm on AMD 64 Debian 10 (Testing). I've tested both using the native install as well as the docker image.

I can build the application and run it manually at `qt-appimage-template/AppDir/usr/bin/qt-appimage-template` but when running `appimage-builder --generate` get this error:

```
INFO:Generator:Analysing application runtime dependencies
INFO:AppRuntimeAnalyser:strace -f -e trace=openat -E LD_DEBUG=libs /home/jack/qt-appimage-template/AppDir/usr/bin/qt-appimage-template $@
INFO:Generator:Guessing APT configuration
INFO:dpkg-query:/usr/bin/dpkg-query -S
WARNING:dpkg-query:dpkg-query: error: --search needs at least one file name pattern argument
WARNING:dpkg-query:
WARNING:dpkg-query:Use --help for help about querying packages.
Traceback (most recent call last):
  File "/usr/local/bin/appimage-builder", line 8, in <module>
    sys.exit(__main__())
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/__main__.py", line 77, in __main__
    generator = RecipeGenerator()
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/generator/generator.py", line 69, in __init__
    self.apt_includes = AptRecipeGenerator.resolve_includes(
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/generator/apt_recipe_generator.py", line 41, in resolve_includes
    packages = AptRecipeGenerator._map_files_to_packages(runtime_libs)
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/generator/apt_recipe_generator.py", line 50, in _map_files_to_packages
    packages = dpkg_query.search(runtime_libs)
  File "/usr/local/lib/python3.9/dist-packages/appimagebuilder/commands/dpkg_query.py", line 31, in search
    raise DpkgQueryError("Package lockup failed")
appimagebuilder.commands.dpkg_query.DpkgQueryError: Package lockup failed
```

I'm using the default arguments for basic information:

```
~/qt-appimage-template$ appimage-builder --generate
INFO:Generator:Searching AppDir
INFO:Generator:Searching desktop entries
INFO:Generator:Reading desktop entry: /home/jack/qt-appimage-template/AppDir/usr/share/applications/QtQuickControls2Application.desktop
Basic Information :
? ID [Eg: com.example.app] : QtQuickControls2Application
? Application Name : SimpleQtApp
? Icon : QtQuickControls2Application
? Version : latest
? Executable path relative to AppDir [usr/bin/app] : usr/bin/qt-appimage-templat
e
? Arguments [Default: $@] : $@
? Update Information [Default: guess] : guess
? Architecture : amd64
```

I'm not totally convinvced that it's not my install, but do you have any idea of things to try? Thanks for your help!

**Comment by azubieta** [comment]
I was able to reproduce the issue. `strace` is missing in your system and in the appimage-builder install instructions. Please install it and try again.

Also a better error message would could help you debug. Working on it right now.

**Comment by azubieta** [comment]
Done, please try again using the latest code from master.

**Comment by zesoft23** [comment]
That fixed it! Really appreciate it! I didn't see the error message when I ran without strace though? Should it also be added here?
https://appimage-builder.readthedocs.io/en/latest/intro/install.html

**Comment by azubieta** [comment]
> I didn't see the error message when I ran without strace though?

Did you upgraded appimage-builder and removed strace? The check was added to the generate method only, so if you are running `appimage-builder` without the `--generate` it will not be required.

>  Should it also be added here?

It's done, I just pushed to the wrong repo.

**Comment by zesoft23** [comment]
Yep! That fixed it. Appreciate your help again!

**Comment by stormchaser3000** [comment]
I am running into this issue when trying to build an armhf package in a debian buster chroot.

I am trying to package the old deprecated appimaged codebase for my Raspberry Pi running Slackware ARM (armv7hl) using an amd64 machine with an armhf chroot.

**Comment by azubieta** [comment]
@stormchaser3000 the '--generate' feature needs to be able to run the application in order to analyze the runtime dependencies. In a cross compilation environment this is usually not possible. But you can still create a recipe manually, [here](https://www.opencode.net/azubieta/dekko-appimage/blob/master/appimage-arm64.yml)  is one for arm64 that you can adapt to armhf.

Fell free to ping me on the #appimage irc channel if you have any other questions
