### ISSUE TITLE
Support static linked binaries as entrypoint

### ISSUE THREAD

**Issue by azubieta** [AppImageCrafters/appimage-builder#8]
Currently `ld.so` is used to `exec` the app main binary but in some cases, such binary is statically linked therefore `ld.so` fails. 
 
Detect when statically linked main binary is used and don't call `ld.so` on it.

**Comment by luis-lavaire** [comment]
You could test `ldd`'s output while creating the AppDir:

```
$ ldd my-static-bin
        not a dynamic executable
$ echo $?
1
```

If `ldd` fails, it's because the application is not a dynamically linked binary.

**Comment by azubieta** [comment]
`ldd` only works for ELF files build for the same architecture it was built. `file`, in the other hand, is more portable and it's already a dependency of `appimagetool`.
