### ISSUE TITLE
Pacman : Architecture field value is ignored

### ISSUE THREAD

**Issue by anupam-git** [AppImageCrafters/appimage-builder#87]
On trying to cross build an aarch64 AppImage, the `Architecture` field is ignored and defaults to `auto` in `appimage-builder-cache/pacman/pacman.conf` file.

Example Snippet : 

```
pacman:
    Architecture: aarch64
    repositories:
      core:
        ...
```

**Comment by azubieta** [comment]
@anupam-git finally I was able to spend some time on this. Could you please validate that the changes in #122 fix the issue?
