### ISSUE TITLE
Wrong creation of PATH in .env

### ISSUE THREAD

**Issue by MitterdorferMathias** [AppImageCrafters/appimage-builder#88]
Currently in `.env` (appimage-builder version 0.8.2)
`PATH=$APPDIR/...:$PATH:$APPDIR/...:$PATH:$APPDIR/...:$PATH:...`

In my opinion `$PATH` should only be present once as last argument.
`PATH=$APPDIR/...:$APPDIR/...:$APPDIR/...:...:$PATH`

**Comment by azubieta** [comment]
Your guess is right. I'll fix it ASAP
Thanks for reporting.

**Comment by azubieta** [comment]
Please try again using the latest code from master and reopen the issue if required.
