### ISSUE TITLE
ModuleNotFoundError: No module named 'AppImageBuilder'

### ISSUE THREAD

**Issue by olof-nord** [AppImageCrafters/appimage-builder#92]
Having installed appimage-installer using `sudo pip3 install appimage-builder`, I run into this issue.

```
appimage-builder --help                                   
Traceback (most recent call last):
  File "/home/olof/.local/bin/appimage-builder", line 15, in <module>
    from AppImageBuilder.__main__ import __main__
ModuleNotFoundError: No module named 'AppImageBuilder'
```

Currently running python `3.9.1`.

Arch Linux, `Linux 5.10.15`, x64

Anyone knows what I might do wrong?

**Comment by azubieta** [comment]
Hi, I tried to reproduce your issue without much success. Same python version.
Could you try installing it from sources `sudo pip3 install git+https://github.com/AppImageCrafters/appimage-builder.git`

**Comment by olof-nord** [comment]
Thanks! That did the trick.
