### ISSUE TITLE
RuntimeError:execution failed with code 100

### ISSUE THREAD

**Issue by hthre7** [AppImageCrafters/appimage-builder#99]
`RuntimeError: "/usr/bin/apt-get install -y --no-install-recommends --simulate libc6:amd64 zlib1g:amd64 libstdc++6:amd64" execution failed with code 100`

linux mint 19.3 , appimage-builder 0.8.5 (both pip & AppImage)

**recipe**: [recipe.yml](https://pastebin.com/fQf1NVS0)
**APT_CONFIG**:[APT_config](https://pastebin.com/09pYZH1h)  /'Conf dpkg:amd64 broken
 Depends:tar:amd64'/

**Comment by azubieta** [comment]
@hthre7 I have pushed a fix to the branch `fix/apt_package_dependencies_not_resolved/99` could you try again using it?

To install the code in that branch run:

`pip install git+https://github.com/AppImageCrafters/appimage-builder.git@issue/34/oscar`

**Comment by hthre7** [comment]
@azubieta 
> `pip install git+https://github.com/AppImageCrafters/appimage-builder.git@issue/34/oscar`

`error: pathspec 'issue/34/oscar' did not match any file(s) known to git`
tried addig using commit but didnt install it just checked the requirement
`pip install git+https://github.com/AppImageCrafters/appimage-builder.git@64c6a9ec38e8dc213d167745512a390c2ebffbe1`

**Comment by azubieta** [comment]
Sorry copy I made a copy paste error, the right path should be:

`pip install git+https://github.com/AppImageCrafters/appimage-builder.git@fix/apt_package_dependencies_not_resolved/99`

**Comment by hthre7** [comment]
> `pip install git+https://github.com/AppImageCrafters/appimage-builder.git@fix/apt_package_dependencies_not_resolved/99`

I add by branch but when it try to make appimage it failed to download the runtime
```bash
INFO:root:Downloading runtime: https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_6
Traceback (most recent call last):
  File "/home/user/.local/bin/appimage-builder", line 33, in <module>
    sys.exit(load_entry_point('appimage-builder==0.8.5', 'console_scripts', 'appimage-builder')())
  File "/home/user/.local/lib/python3.6/site-packages/appimagebuilder/__main__.py", line 114, in __main__
    creator.create()
  File "/home/user/.local/lib/python3.6/site-packages/appimagebuilder/appimage.py", line 52, in create
    self._download_runtime_if_required(runtime_path, runtime_url)
  File "/home/user/.local/lib/python3.6/site-packages/appimagebuilder/appimage.py", line 68, in _download_runtime_if_required
    request.urlretrieve(runtime_url, runtime_path)
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by azubieta** [comment]
I wonder why it's trying to download from `https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_6
` heads up on the end `x86_6` where it should be `x86_64`. Are you writing it properly in the yaml file ?

**Comment by hthre7** [comment]
> I wonder why it's trying to download from `https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_6 ` heads up on the end `x86_6` where it should be `x86_64`. Are you writing it properly in the yaml file ?

oh yes it was x86_6.
thanks

**Comment by azubieta** [comment]
It seems that AppImage builder whats able to resolve some libraries from your system. This is normal if the libraries are not installed from a deb package. I opened an issue to improve how this issue is handled.

But the solution would be to manually create your recipe file, you can check the examples at https://appimage-builder.readthedocs.io/en/latest/ for inspiration.

**Comment by hthre7** [comment]
Thanks. I just  posted to point out the issue, cause I already make the recipe manually and created the appimage.
but as I mentiond above that there some theming issue that appimage is don't have access to system gtk or it need a newer version of gtk(or env variable)

**Comment by azubieta** [comment]
Using the system theme is an issue for all portable formats. The reason is that some libraries (plugins) from the system need to be loaded and those are not always available or compatible that's why the safe way is to embed a fixed theme.

If you want to dig a bit in the topic you can check how GTK applications are configured at runtime and play with the runtime env section. Notice that you don't need to rebuild the whole AppImage to apply the changes, instead you can modify the file "AppDir/.env"
